name: Update Dotnet Versions

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "0 8 * * *" # Runs daily at 8 AM UTC

jobs:
  update-dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Ensure full history for branch checks

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check if branch exists
        id: check_branch
        run: |
          if git show-ref --quiet refs/heads/update_dotnet; then
            echo "BRANCH_EXISTS=true" >> $GITHUB_ENV
            echo "branch exists"
            git checkout update_dotnet
          else
            echo "BRANCH_EXISTS=false" >> $GITHUB_ENV
            echo "branch does not exist"
            git checkout -b update_dotnet
          fi

      - uses: actions/checkout@v5
      - uses: wimpysworld/nothing-but-nix@v6
      - uses: DeterminateSystems/nix-installer-action@v19

      - name: Run update script
        run: nix run .#dotnet-update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          commit-message: "feat: dotnet update"
          branch: create-pull-request/dotnet
          delete-branch: true
          assignees: konradmalik
          title: "Update dotnet versions"
          body: |
            Automated update of dotnet versions.

            By [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.
